import { IProduct } from '../types/IProduct';

export const cars: IProduct[] = [
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'AAAAAA',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/1.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: ' 1',
        title: 'SSSSSSSSSS',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/2.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'DDDDDD',
        count: 5,
        year: '2021',
        color: 'Red',
        image: '/assets/images/3.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'XXXXX',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/1.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'CCCCCC',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/2.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'VVVVVVVVV',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/3.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'BBBBBBB',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/3.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'AAAAAA',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/1.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: ' 1',
        title: 'SSSSSSSSSS',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/2.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'DDDDDD',
        count: 5,
        year: '2021',
        color: 'Red',
        image: '/assets/images/3.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'XXXXX',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/1.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'CCCCCC',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/2.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'VVVVVVVVV',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/3.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
    {
        id: '1',
        title: 'BBBBBBB',
        count: 5,
        year: '2021',
        color: 'Red',
        image: 'assets/images/3.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50000,
    },
];
