import { IProduct } from '../types/IProduct';

export const cars: IProduct[] = [
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Q8',
        count: 5,
        year: '2021',
        color: 'Yellow',
        image: 'assets/images/1.jpg',
        make: 'AUDI',
        vehicle: 'SUV',
        fuel: 'Diesel',
        price: 150,
        favorites: true,
    },
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-3b0d7b3dcb6d',
        title: 'SQ7',
        count: 4,
        year: '2021',
        color: 'Grey',
        image: 'assets/images/2.jpg',
        make: 'AUDI',
        vehicle: 'Estate Car',
        fuel: 'Diesel',
        price: 140,
        favorites: false,
    },
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-4b0d7b3dcb6d',
        title: 'X6',
        count: 3,
        year: '2017',
        color: 'Red',
        image: '/assets/images/3.jpg',
        make: 'BMW',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 50,
        favorites: false,
    },
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-5b0d7b3dcb6d',
        title: 'G11-7',
        count: 2,
        year: '2021',
        color: 'Black',
        image: 'assets/images/4.jpg',
        make: 'BMW',
        vehicle: 'Sedan',
        fuel: 'Petrol',
        price: 80,
        favorites: false,
    },
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-6b0d7b3dcb6d',
        title: 'X3',
        count: 1,
        year: '2021',
        color: 'White',
        image: 'assets/images/5.jpg',
        make: 'BMW',
        vehicle: 'SUV',
        fuel: 'Diesel',
        price: 90,
        favorites: false,
    },
    {
        id: '9b1deb4d-3b7d-4bad-9bdd-7b0d7b3dcb6d',
        title: 'Focus',
        count: 5,
        year: '2021',
        color: 'Blue',
        image: 'assets/images/6.jpg',
        make: 'Ford',
        vehicle: 'Sedan',
        fuel: 'Petrol',
        price: 25,
        favorites: false,
    },
    {
        id: '8b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Galaxy-III',
        count: 5,
        year: '2015',
        color: 'Black',
        image: 'assets/images/7.jpg',
        make: 'Ford',
        vehicle: 'Van',
        fuel: 'Diesel',
        price: 30,
        favorites: true,
    },
    {
        id: '7b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'S-MAX II',
        count: 5,
        year: '2015',
        color: 'Grey',
        image: 'assets/images/8.jpg',
        make: 'Ford',
        vehicle: 'Van',
        fuel: 'Diesel',
        price: 25,
        favorites: false,
    },
    {
        id: '6b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'CLA-220',
        count: 5,
        year: '2018',
        color: 'Black',
        image: 'assets/images/9.jpg',
        make: 'Mercedes',
        vehicle: 'Sedan',
        fuel: 'Petrol',
        price: 130,
        favorites: false,
    },
    {
        id: '5b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'GLE-580',
        count: 5,
        year: '2020',
        color: 'Red',
        image: '/assets/images/10.jpg',
        make: 'Mercedes',
        vehicle: 'SUV',
        fuel: 'Petrol',
        price: 140,
        favorites: true,
    },
    {
        id: '4b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Vito',
        count: 5,
        year: '2020',
        color: 'Red',
        image: 'assets/images/11.jpg',
        make: 'Mercedes',
        vehicle: 'Van',
        fuel: 'Diesel',
        price: 70,
        favorites: false,
    },
    {
        id: '3b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Espace-IV',
        count: 1,
        year: '2015',
        color: 'Black',
        image: 'assets/images/12.jpg',
        make: 'Renault',
        vehicle: 'Van',
        fuel: 'Diesel',
        price: 35,
        favorites: true,
    },
    {
        id: '2b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Sharan II',
        count: 1,
        year: '2017',
        color: 'Yellow',
        image: 'assets/images/13.jpg',
        make: 'Volkswagen',
        vehicle: 'Van',
        fuel: 'Diesel',
        price: 170,
        favorites: false,
    },
    {
        id: '1b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Leaf II',
        count: 3,
        year: '2020',
        color: 'White',
        image: 'assets/images/14.jpg',
        make: 'Nissan',
        vehicle: 'Sedan',
        fuel: 'Electric',
        price: 50,
        favorites: false,
    },
    {
        id: '7b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'W246',
        count: 5,
        year: '2021',
        color: 'Black',
        image: 'assets/images/15.jpg',
        make: 'Mercedes',
        vehicle: 'Sedan',
        fuel: 'Gas',
        price: 120,
        favorites: true,
    },
    {
        id: '6b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Traveller',
        count: 5,
        year: '2021',
        color: 'Black',
        image: 'assets/images/16.jpg',
        make: 'Peugeot',
        vehicle: 'Van',
        fuel: 'Diesel',
        price: 70,
        favorites: false,
    },
    {
        id: '5b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Insignia B GSi ',
        count: 5,
        year: '2021',
        color: 'White',
        image: '/assets/images/17.jpg',
        make: 'Opel',
        vehicle: 'Sedan',
        fuel: 'Petrol',
        price: 140,
        favorites: true,
    },
    {
        id: '4b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'CX-60',
        count: 5,
        year: '2020',
        color: 'White',
        image: 'assets/images/18.jpg',
        make: 'Mazda',
        vehicle: 'SUV',
        fuel: 'Diesel',
        price: 70,
        favorites: false,
    },
    {
        id: '3b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: 'Grandland Ultimate',
        count: 1,
        year: '2021',
        color: 'Blue',
        image: 'assets/images/19.jpg',
        make: 'Opel',
        vehicle: 'SUV',
        fuel: 'Diesel',
        price: 35,
        favorites: false,
    },
    {
        id: '2b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: '5008-GT',
        count: 1,
        year: '2017',
        color: 'Black',
        image: 'assets/images/20.jpg',
        make: 'Peugeot',
        vehicle: 'SUV',
        fuel: 'Diesel',
        price: 170,
        favorites: false,
    },
    {
        id: '1b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d',
        title: '6 SKYACTIV-D',
        count: 3,
        year: '2020',
        color: 'White',
        image: 'assets/images/21.jpg',
        make: 'Mazda',
        vehicle: 'Estate Car',
        fuel: 'Diesel',
        price: 50,
        favorites: true,
    },
];
